In [4]:
import pandas as pd
melb_data = pd.read_csv('data/melb_new.csv', sep=';', decimal='.')

In [8]:
round(melb_data['Price'].max())

9000000

In [11]:
# Представим, что риэлторская ставка для всех компаний за продажу недвижимости составляет 12%. 
# Найдём общую прибыльность риэлторского бизнеса в Мельбурне. Результат округлим до сотых

rate = 0.12
income = melb_data['Price'].sum() * rate
print('Total income of real estate agencies:', round(income, 2))

Total income of real estate agencies: 1752934775.88

In [15]:
# Найдём, насколько медианная площадь территории отличается от её среднего значения. 
# Вычислим модуль разницы между медианой и средним и разделим результат на среднее, чтобы получить отклонение в долях

landsize_median = melb_data['Landsize'].median()
landsize_mean = melb_data['Landsize'].mean()
print((abs(landsize_median - landsize_mean)) / landsize_mean)

0.21205713983546193

In [22]:
melb_data['Rooms'].mode()
melb_data['Price'].mode()

0    1100000.0
Name: Price, dtype: float64

In [28]:
# Создание маски

mask = melb_data['Price'] > 2000000
melb_data[mask].head()
melb_data[melb_data['Price'] > 2000000]

,Unnamed: 0,index,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,...,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Coordinates
80,80,80,Albert Park,112 Beaconsfield Pde,3,h,2850000.0,PI,Buxton,4/03/2017,...,0,211.0,198.0,1890,Port Phillip,-37.84810,144.94990,Southern Metropolitan,3280,"-37.8481, 144.9499"
85,85,85,Albert Park,104 Richardson St,4,h,2300000.0,S,Marshall,7/05/2016,...,1,153.0,180.0,1880,Port Phillip,-37.84470,144.95230,Southern Metropolitan,3280,"-37.8447, 144.9523"
88,88,88,Albert Park,29 Faussett St,2,h,2120000.0,S,Greg,10/09/2016,...,1,199.0,107.0,1900,Port Phillip,-37.84220,144.95540,Southern Metropolitan,3280,"-37.8422, 144.9554"
92,92,92,Albert Park,2 Dundas Pl,3,h,2615000.0,S,Cayzer,10/12/2016,...,1,177.0,181.0,1880,Port Phillip,-37.84150,144.95850,Southern Metropolitan,3280,"-37.8415, 144.9585"
93,93,93,Albert Park,23 Finlay St,5,h,2100000.0,S,Greg,10/12/2016,...,1,237.0,126.0,1970,Port Phillip,-37.84360,144.95570,Southern Metropolitan,3280,"-37.8436, 144.9557"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13521,13521,13521,Port Melbourne,44 Garton St,4,t,2455000.0,SP,Marshall,26/08/2017,...,2,123.0,0.0,2010,NaN,-37.83349,144.94840,Southern Metropolitan,8648,"-37.83349, 144.9484"
13523,13523,13523,Prahran,69 Greville St,4,h,2668000.0,S,Biggin,26/08/2017,...,2,383.0,126.0,1970,NaN,-37.84879,144.98882,Southern Metropolitan,7717,"-37.84879, 144.98882"
13553,13553,13553,Surrey Hills,20 Albert Cr,4,h,2720000.0,S,Kay,26/08/2017,...,2,1005.0,126.0,1920,NaN,-37.82421,145.10352,Southern Metropolitan,5457,"-37.82421, 145.10352"
13555,13555,13555,Surrey Hills,3 Oak St,4,h,3100000.0,VB,Marshall,26/08/2017,...,3,832.0,126.0,1970,NaN,-37.83564,145.10919,Southern Metropolitan,5457,"-37.83564, 145.10919"
13578,13578,13578,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,...,5,866.0,157.0,1920,NaN,-37.85908,144.89299,Western Metropolitan,6380,"-37.85908, 144.89299"

In [30]:
# Дома с ценой менее 300 тысяч, у которых либо число комнат равно 3 либо площадь домов более 100 квадратных метров

melb_data[((melb_data['Rooms'] == 3) | (melb_data['BuildingArea'] > 100)) & (melb_data['Price'] < 300000)].shape[0]

68

In [33]:
# Максимальное количество комнат в таунхаусах

melb_data[melb_data['Type'] == 't']['Rooms'].max()

5

In [35]:
# Найдём медианную площадь здания у объектов, чья цена выше средней. 
# Для того чтобы оградить наш код от нагромождений, предварительно создадим переменную со средней ценой
melb_average = melb_data['Price'].mean()
melb_data[melb_data['Price'] > melb_average]['BuildingArea'].median()

126.0